title: Kursledarprogram inom West Coast Swing
description: WCS Umeås kursledarprogram för nya kursledare
repository: wcs-umea/kursledarprogram
theme: jekyll-theme-cayman
github:
  is_project_page: false