project:
  type: website


# several branches can be specified here
branches:
  - branch: "release-2024-2025"     # change this to the release branch
    output-dir: "2024-2025"         # change this to year and month of the course instance

website:
  title: "Kursledarprogram WCS 2024-2025"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 30px
    search: true
    contents: 
      - index.qmd 
      - setup.qmd
      - schedule.qmd
      - resources.qmd
  navbar:
    background: "#800080"
    logo: "img/wcsumea-logo.png"
  favicon: "img/wcsumea-logo.png"
  body-footer: footer.html


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

