---
title: "Upplägg"
date: today
---

## Upplägg av programmet

Programmet består av flera olika aktiviteter som löper under flera månader. Två helger är schemalagda på plats i Umeå, seminarierna sker online, och praktiken kan göras på valfri plats. Deltagarna på programmet förväntas delta i alla aktiviteter.

#### Helgkurs: Kursledarutbildning Steg 1
**Var:** På plats i Umeå  
Helgkurs där vi kommer att starta igång programmet med en hel helg. Vi går igenom grunderna du behöver kunna som kursledare. Målet med denna kurs är att du ska ha de verktyg och turer du behöver för att börja hålla nybörjarkurser och prova på kurser.

#### Seminarie: Pedagogik och lärande
**Var:** Online  
I detta seminarie kommer vi gå igenom grunderna i pedagogik och hur våra deltagare bäst lär sig. Seminariet består av en presentation följt av en diskussion i mindre grupper.


#### Seminarie: Din utveckling som kursledare
**Var:** Online  
I detta seminarie kommer vi diskutera en kursledares utveckling, och de olika stadierna som alla går igenom. Detta följs av en diskussion om din egen utveckling som kursledare och vilket stadie du befinner dig i.

#### Seminarie: Din roll som ledare och förebild
**Var:** Online  
I detta seminarie kommer vi gå igenom och diskutera hur du som kursledare har en viktig roll som ledare och förebild i ditt community, och hur vi på bästa sätt hanterar detta.


#### Hands-on / Praktik
**Var:** Valfritt  
Under programmets gång föväntas ni delta och observera befintliga kurser och kursledare, för att själva reflektera över hur de lägger upp ett kurstillfälle. Nedan är de aktiviteter som ingår:

**Observera:**

- Observera minst ett kurstillfälle (Nybörjarkurs/Prova på)
- Utvärdera vad du såg utifrån ett antal frågor
- Diskutera och reflektera med kursledaren efteråt

**Praktisera:**

- Håll minst ett kurstillfälle med ordinarie kursledare
- Planera tillfället tillsammans med ordinarie kursledare, använd dina lärdomar från observationstillfället
- Utvärdera kurstillfället tillsammans med kursledaren
- Dokumentera dina upplevelser i en kort reflektionsrapport


#### Helgkurs: Kursledarutbildning Steg 2
**Var:** På plats i Umeå  
Helgkurs där vi kommer att fortsätta bygga på de kunskaper vi lärt oss under programmet, och dyka djupare ner i teknik och turer som passar för fortsättningskurser. Målet med kursen är att deltagarna ska kunna hålla fortsättningskurser.